spring:
  datasource:
    name : gestionstockdb
    url: jdbc:h2:file:./src/main/resources/database/gestionstockdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  ## Specify DBMS
  jpa:
    show-sql: true
    properties:
      hibernate:
        session_factory:
          interceptor: com.bouali.gestiondestock.interceptor.Interceptor

    # Hibernate DDL Auto (create, create-drop, update)
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.H2Dialect

server:
  port: 8081

flickr:
  apiKey: e6017aef7bebeffc113de04efec554b4
  apiSecret: a2e10f69ece5c67c
  appKey: 72157718699655397-a36ae267891db7e7
  appSecret: 04e870e57e18c55b
